import { currencyType } from '../types/types'

export const currency: currencyType[] = [
	{
		name: 'USD',
		value: '$',
		countries: ['United States', 'Ecuador', 'El Salvador', 'Zimbabwe'],
	},
	{
		name: 'EUR',
		value: '€',
		countries: [
			'Austria',
			'Belgium',
			'Cyprus',
			'Estonia',
			'Finland',
			'France',
			'Germany',
			'Greece',
			'Ireland',
			'Italy',
			'Latvia',
			'Lithuania',
			'Luxembourg',
			'Malta',
			'Netherlands',
			'Portugal',
			'Slovakia',
			'Slovenia',
		],
	},
	{ name: 'UAH', value: '₴', countries: ['Ukraine'] },

	{ name: 'AED', value: 'د.إ', countries: ['United Arab Emirates'] },
	{ name: 'AFN', value: '؋', countries: ['Afghanistan'] },
	{ name: 'ALL', value: 'L', countries: ['Albania'] },
	{ name: 'AMD', value: '֏', countries: ['Armenia'] },
	{ name: 'ANG', value: 'ƒ', countries: ['Curaçao', 'Sint Maarten'] },
	{ name: 'AOA', value: 'Kz', countries: ['Angola'] },
	{ name: 'ARS', value: '$', countries: ['Argentina'] },
	{
		name: 'AUD',
		value: '$',
		countries: ['Australia', 'Kiribati', 'Nauru', 'Tuvalu'],
	},
	{ name: 'AWG', value: 'ƒ', countries: ['Aruba'] },
	{ name: 'AZN', value: '₼', countries: ['Azerbaijan'] },
	{ name: 'BAM', value: 'KM', countries: ['Bosnia and Herzegovina'] },
	{ name: 'BBD', value: '$', countries: ['Barbados'] },
	{ name: 'BDT', value: '৳', countries: ['Bangladesh'] },
	{ name: 'BGN', value: 'лв', countries: ['Bulgaria'] },
	{ name: 'BHD', value: '.د.ب', countries: ['Bahrain'] },
	{ name: 'BIF', value: 'FBu', countries: ['Burundi'] },
	{ name: 'BMD', value: '$', countries: ['Bermuda'] },
	{ name: 'BND', value: '$', countries: ['Brunei'] },
	{ name: 'BOB', value: 'Bs.', countries: ['Bolivia'] },
	{ name: 'BRL', value: 'R$', countries: ['Brazil'] },
	{ name: 'BSD', value: '$', countries: ['Bahamas'] },
	{ name: 'BTN', value: 'Nu.', countries: ['Bhutan'] },
	{ name: 'BWP', value: 'P', countries: ['Botswana'] },
	{ name: 'BYN', value: 'Br', countries: ['Belarus'] },
	{ name: 'BZD', value: '$', countries: ['Belize'] },
	{ name: 'CAD', value: '$', countries: ['Canada'] },
	{ name: 'CDF', value: 'FC', countries: ['Democratic Republic of the Congo'] },
	{ name: 'CHF', value: 'Fr', countries: ['Switzerland', 'Liechtenstein'] },
	{ name: 'CLP', value: '$', countries: ['Chile'] },
	{ name: 'CNY', value: '¥', countries: ['China'] },
	{ name: 'COP', value: '$', countries: ['Colombia'] },
	{ name: 'CRC', value: '₡', countries: ['Costa Rica'] },
	{ name: 'CUP', value: '$', countries: ['Cuba'] },
	{ name: 'CVE', value: '$', countries: ['Cape Verde'] },
	{ name: 'CZK', value: 'Kč', countries: ['Czech Republic'] },
	{ name: 'DJF', value: 'Fdj', countries: ['Djibouti'] },
	{
		name: 'DKK',
		value: 'kr',
		countries: ['Denmark', 'Faroe Islands', 'Greenland'],
	},
	{ name: 'DOP', value: '$', countries: ['Dominican Republic'] },
	{ name: 'DZD', value: 'د.ج', countries: ['Algeria'] },
	{ name: 'EGP', value: '£', countries: ['Egypt'] },
	{ name: 'ERN', value: 'Nfk', countries: ['Eritrea'] },
	{ name: 'ETB', value: 'Br', countries: ['Ethiopia'] },
	{ name: 'FJD', value: '$', countries: ['Fiji'] },
	{ name: 'FKP', value: '£', countries: ['Falkland Islands'] },
	{ name: 'FOK', value: 'kr', countries: ['Faroe Islands'] },
	{
		name: 'GBP',
		value: '£',
		countries: ['United Kingdom', 'Guernsey', 'Isle of Man', 'Jersey'],
	},
	{ name: 'GEL', value: '₾', countries: ['Georgia'] },
	{ name: 'GGP', value: '£', countries: ['Guernsey'] },
	{ name: 'GHS', value: '₵', countries: ['Ghana'] },
	{ name: 'GIP', value: '£', countries: ['Gibraltar'] },
	{ name: 'GMD', value: 'D', countries: ['Gambia'] },
	{ name: 'GNF', value: 'FG', countries: ['Guinea'] },
	{ name: 'GTQ', value: 'Q', countries: ['Guatemala'] },
	{ name: 'GYD', value: '$', countries: ['Guyana'] },
	{ name: 'HKD', value: '$', countries: ['Hong Kong'] },
	{ name: 'HNL', value: 'L', countries: ['Honduras'] },
	{ name: 'HRK', value: 'kn', countries: ['Croatia'] },
	{ name: 'HTG', value: 'G', countries: ['Haiti'] },
	{ name: 'HUF', value: 'Ft', countries: ['Hungary'] },
	{ name: 'IDR', value: 'Rp', countries: ['Indonesia'] },
	{ name: 'ILS', value: '₪', countries: ['Israel', 'Palestinian Territories'] },
	{ name: 'IMP', value: '£', countries: ['Isle of Man'] },
	{ name: 'INR', value: '₹', countries: ['India'] },
	{ name: 'IQD', value: 'ع.د', countries: ['Iraq'] },
	{ name: 'IRR', value: '﷼', countries: ['Iran'] },
	{ name: 'ISK', value: 'kr', countries: ['Iceland'] },
	{ name: 'JEP', value: '£', countries: ['Jersey'] },
	{ name: 'JMD', value: '$', countries: ['Jamaica'] },
	{ name: 'JOD', value: 'د.ا', countries: ['Jordan'] },
	{ name: 'JPY', value: '¥', countries: ['Japan'] },
	{ name: 'KES', value: 'Sh', countries: ['Kenya'] },
	{ name: 'KGS', value: 'лв', countries: ['Kyrgyzstan'] },
	{ name: 'KHR', value: '៛', countries: ['Cambodia'] },
	{ name: 'KID', value: '$', countries: ['Kiribati'] },
	{ name: 'KMF', value: 'CF', countries: ['Comoros'] },
	{ name: 'KRW', value: '₩', countries: ['South Korea'] },
	{ name: 'KWD', value: 'د.ك', countries: ['Kuwait'] },
	{ name: 'KYD', value: '$', countries: ['Cayman Islands'] },
	{ name: 'KZT', value: '₸', countries: ['Kazakhstan'] },
	{ name: 'LAK', value: '₭', countries: ['Laos'] },
	{ name: 'LBP', value: 'ل.ل', countries: ['Lebanon'] },
	{ name: 'LKR', value: 'Rs', countries: ['Sri Lanka'] },
	{ name: 'LRD', value: '$', countries: ['Liberia'] },
	{ name: 'LSL', value: 'L', countries: ['Lesotho'] },
	{ name: 'LYD', value: 'ل.د', countries: ['Libya'] },
	{ name: 'MAD', value: 'د.م.', countries: ['Morocco'] },
	{ name: 'MDL', value: 'L', countries: ['Moldova'] },
	{ name: 'MGA', value: 'Ar', countries: ['Madagascar'] },
	{ name: 'MKD', value: 'ден', countries: ['North Macedonia'] },
	{ name: 'MMK', value: 'K', countries: ['Myanmar'] },
	{ name: 'MNT', value: '₮', countries: ['Mongolia'] },
	{ name: 'MOP', value: 'P', countries: ['Macau'] },
	{ name: 'MRU', value: 'UM', countries: ['Mauritania'] },
	{ name: 'MUR', value: '₨', countries: ['Mauritius'] },
	{ name: 'MVR', value: 'Rf', countries: ['Maldives'] },
	{ name: 'MWK', value: 'MK', countries: ['Malawi'] },
	{ name: 'MXN', value: '$', countries: ['Mexico'] },
	{ name: 'MYR', value: 'RM', countries: ['Malaysia'] },
	{ name: 'MZN', value: 'MT', countries: ['Mozambique'] },
	{ name: 'NAD', value: '$', countries: ['Namibia'] },
	{ name: 'NGN', value: '₦', countries: ['Nigeria'] },
	{ name: 'NIO', value: 'C$', countries: ['Nicaragua'] },
	{ name: 'NOK', value: 'kr', countries: ['Norway', 'Svalbard and Jan Mayen'] },
	{ name: 'NPR', value: '₨', countries: ['Nepal'] },
	{
		name: 'NZD',
		value: '$',
		countries: [
			'New Zealand',
			'Cook Islands',
			'Niue',
			'Pitcairn Islands',
			'Tokelau',
		],
	},
	{ name: 'OMR', value: '﷼', countries: ['Oman'] },
	{ name: 'PAB', value: 'B/.', countries: ['Panama'] },
	{ name: 'PEN', value: 'S/', countries: ['Peru'] },
	{ name: 'PGK', value: 'K', countries: ['Papua New Guinea'] },
	{ name: 'PHP', value: '₱', countries: ['Philippines'] },
	{ name: 'PKR', value: '₨', countries: ['Pakistan'] },
	{ name: 'PLN', value: 'zł', countries: ['Poland'] },
	{ name: 'PYG', value: '₲', countries: ['Paraguay'] },
	{ name: 'QAR', value: '﷼', countries: ['Qatar'] },
	{ name: 'RON', value: 'lei', countries: ['Romania'] },
	{ name: 'RSD', value: 'din', countries: ['Serbia'] },
	{ name: 'RUB', value: '₽', countries: ['Russia'] },
	{ name: 'RWF', value: 'FRw', countries: ['Rwanda'] },
	{ name: 'SAR', value: '﷼', countries: ['Saudi Arabia'] },
	{ name: 'SBD', value: '$', countries: ['Solomon Islands'] },
	{ name: 'SCR', value: '₨', countries: ['Seychelles'] },
	{ name: 'SDG', value: 'ج.س.', countries: ['Sudan'] },
	{ name: 'SEK', value: 'kr', countries: ['Sweden'] },
	{ name: 'SGD', value: '$', countries: ['Singapore'] },
	{ name: 'SHP', value: '£', countries: ['Saint Helena'] },
	{ name: 'SLE', value: 'Le', countries: ['Sierra Leone'] },
	{ name: 'SLL', value: 'Le', countries: ['Sierra Leone'] },
	{ name: 'SOS', value: 'Sh', countries: ['Somalia'] },
	{ name: 'SRD', value: '$', countries: ['Suriname'] },
	{ name: 'SSP', value: '£', countries: ['South Sudan'] },
	{ name: 'STN', value: 'Db', countries: ['São Tomé and Príncipe'] },
	{ name: 'SYP', value: '£', countries: ['Syria'] },
	{ name: 'SZL', value: 'L', countries: ['Eswatini (Swaziland)'] },
	{ name: 'THB', value: '฿', countries: ['Thailand'] },
	{ name: 'TJS', value: 'SM', countries: ['Tajikistan'] },
	{ name: 'TMT', value: 'T', countries: ['Turkmenistan'] },
	{ name: 'TND', value: 'د.ت', countries: ['Tunisia'] },
	{ name: 'TOP', value: 'T$', countries: ['Tonga'] },
	{ name: 'TRY', value: '₺', countries: ['Turkey'] },
	{ name: 'TTD', value: '$', countries: ['Trinidad and Tobago'] },
	{ name: 'TVD', value: '$', countries: ['Tuvalu'] },
	{ name: 'TWD', value: 'NT$', countries: ['Taiwan'] },
	{ name: 'TZS', value: 'Sh', countries: ['Tanzania'] },
	{ name: 'UGX', value: 'USh', countries: ['Uganda'] },
	{ name: 'UYU', value: '$U', countries: ['Uruguay'] },
	{ name: 'UZS', value: 'лв', countries: ['Uzbekistan'] },
	{ name: 'VES', value: 'Bs.', countries: ['Venezuela'] },
	{ name: 'VND', value: '₫', countries: ['Vietnam'] },
	{ name: 'VUV', value: 'VT', countries: ['Vanuatu'] },
	{ name: 'WST', value: 'T', countries: ['Samoa'] },
	{
		name: 'XAF',
		value: 'FCFA',
		countries: [
			'Central African Economic and Monetary Community (CEMAC) countries',
		],
	},
	{ name: 'XCD', value: '$', countries: ['Eastern Caribbean states'] },
	{
		name: 'XDR',
		value: 'XDR',
		countries: ['International Monetary Fund (IMF)'],
	},
	{
		name: 'XOF',
		value: 'CFA',
		countries: ['West African Economic and Monetary Union (WAEMU) countries'],
	},
	{
		name: 'XPF',
		value: '₣',
		countries: ['French overseas territories (Pacific)'],
	},
	{ name: 'YER', value: '﷼', countries: ['Yemen'] },
	{ name: 'ZAR', value: 'R', countries: ['South Africa'] },
	{ name: 'ZMW', value: 'ZK', countries: ['Zambia'] },
	{ name: 'ZWL', value: '$', countries: ['Zimbabwe'] },
]
